spring:
  application:
    name: connect-user-details-service
  datasource:
    url: jdbc:mysql://localhost:3306/connect_micro_service
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update      
    properties:
     hibernate:
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
    
server:  port: 8083